name: Deploy Staging

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Conecta na EC2 e faz o deploy em staging
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_STAGING }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY_STAGING }}
          script: |
            if [ -d "/home/ec2-user/app/.git" ]; then
              cd /home/ec2-user/app
              git checkout develop
              git pull origin develop
            else
              git clone -b develop https://github.com/PedroDelmiro13/devops-challenge.git /home/ec2-user/app
              cd /home/ec2-user/app
            fi
            docker build -t lacrei-app:staging .
            docker stop lacrei-app || true
            docker rm lacrei-app || true
            docker run -d --name lacrei-app -p 3000:3000 --restart unless-stopped lacrei-app:staging